# Домашняя работа №1

### Импортируем нужную нам библиотеку - NumPy

In [141]:
import numpy as np # импортирование библиотеки NumPy

### Создатим двумерный список и убедимся, что он таковым является

In [142]:
a = [[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]
print(a)
print(type(a))

[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]
<class 'list'>


### Теперь преобразуем его в тип numpy.ndarray и выведем

In [143]:
a = np.array(a) #переводим классический python список в массив numpy
print(a)


[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


### Как мы видим, вывод не изменился семантически, но визуально, теперь двумерный массив представляется матрицей, проверим тип нашего массива

In [144]:
print(type(a))  # выводим тип массива
print(a.dtype)  # выводим тип данных в массиве

<class 'numpy.ndarray'>
int64


### Наш массив действительно является numpy.ndarray. Теперь попробуем поменять столбцы местами и вывести данный массив

In [145]:
b = np.flip(a, axis=1)  # "переворот" элементов массива по столбцам
print(b)

[[4 3 2 1]
 [4 3 2 1]
 [4 3 2 1]
 [4 3 2 1]]


### Мы получили массив с обратной нумерацией столбцов. Давайте сложим наш исходный массив с получившимся

In [146]:
c = a+b #сложение по правилу сложения матриц
print(c)


[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


### Наш получившийся массив очень похож на матрицу, составленную из единиц, умноженную на 5. Давайте получим такой же вывод, составив матрицу из единиц путём использования np.ones() и вычтем одну из другой

In [147]:
d = np.ones((a.shape), dtype=np.int64) # создаём массив размерами 4x4 со значениями равными единице
d *= 5 # умножим каждый элемент на 5
print(d)


[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [148]:
sub = c-d
print(sub)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### Мы получили квадратную матрицу, составленную из нулей. Давайте проверим, эквивалентна ли она матрице, составленной при помощи np.zeros

In [149]:
print(np.array_equal(sub, np.zeros(sub.shape, dtype=sub.dtype))) # сравниваем sub с np.zeros размером и типом данных как у sub


True


### Мы получили истину!

### Теперь создадим одномерный массив при помощи оператора arange

In [150]:
ar = np.arange(1, 100, 10, dtype=np.int64) # необходимо учесть, что воспринимается множество чисел [a;b)
print(ar)


[ 1 11 21 31 41 51 61 71 81 91]


### Получили массив от 1 до 91 включительно с шагом 10 длинной 10. Теперь давайте расположим данные значения на главной диагонали матрицы, подобно множеству собственных значений для базиса

In [151]:
di = np.diag(ar, k=0)
print(di)


[[ 1  0  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  0  0  0]
 [ 0  0 21  0  0  0  0  0  0  0]
 [ 0  0  0 31  0  0  0  0  0  0]
 [ 0  0  0  0 41  0  0  0  0  0]
 [ 0  0  0  0  0 51  0  0  0  0]
 [ 0  0  0  0  0  0 61  0  0  0]
 [ 0  0  0  0  0  0  0 71  0  0]
 [ 0  0  0  0  0  0  0  0 81  0]
 [ 0  0  0  0  0  0  0  0  0 91]]


### Мы получили квадратную матрицу 10x10, на главной диагонали которой распологаются наши числа. Давайте получим значение, распологающееся на 5ой строке 5ого столбца

In [152]:
def center(a):
    return len(a)//2-1

print(di[center(di)][center(di[0])])

41


### Мы получили значение 41, что соответствует действительности

### Теперь давайте создадим массив из случайного набора чисел от 0 до 1 и найдём его медиану

In [153]:
rand = np.random.random(10) #создаём массив длинной 10 случайных чисел
print(rand)
print(rand.mean()) #выводим медиану

[0.29268431 0.04088072 0.55229215 0.18306856 0.20719108 0.54287887
 0.4093787  0.84965181 0.29210221 0.17670487]
0.3546833280545508


### Создадим некий базис пространства R^2 и найдём собственные числа с векторами при переходе к данному базису

In [154]:
a = np.array([[-12, -6], [2, 6]])
w, v = np.linalg.eig(a)
print("Собственные числа:", *w)
print("Собственные векторы:", *v)

Собственные числа: -11.306623862918073 5.306623862918075
Собственные векторы: [-0.99338878  0.32756127] [ 0.11479868 -0.94482994]
